import random


def create_code(characters, length):
    '''
    (str, int) --> list

    characters: a string made up of the characters wanted in the list
    length: the length of the list to be made

    This function returns a random list of characters of the length specified
    using the characters in the given string.

    >>>create_code('gbryop', 4)
    ['b', 'b', 'g', 'r']
    '''

    code = []

    for a in range(0, length):
        code.append(random.choice(characters))

    return code


def valid(guess, valid_characters, size):
    '''
    (list, str, int) --> boolean

    guess: list made of single character strs that the user creates
    valid_characters: the characters that the guess should use
    size: the length the guess should be

    The function will return True if all the single character strs present in
    the list are also in the valid_characters string and the list is equal
    in length to the given size (int).

    >>>valid(['g', 'b', 'r', 'r'], 'gbryop', 4)
    True
    '''

    count = 0

    if len(guess) == size:
        for item in guess:
            if item in valid_characters:
                count += 1
    else:
        print('The guess can only be 4 characters long.')
        print(' ')
        return False

    if count == size:
        return True
    else:
        print('The guess can only contain the following letters: roygbiv')
        print(' ')
        return False


def find_fully_correct(answer, guess):
    '''
    (list, list) --> list

    answer: the code generated by the program that the user has to correctly
    identify
    guess: the guess submitted by the user of what they think the answer is

    The function will return a list containing a 'b' for every colour that is
    in the same position in the guess and in the answer code.

    >>>find_fully_correct(['r', 'b', 'g', 'y'], ['o', 'b', 'g', 'r'])
    ['b']
    '''

    length = len(answer)
    feedback = []

    for index in range(0, length):
        if answer[index] == guess[index]:
            feedback.append('b')

    return feedback


def remove_fully_correct(list1, list2):
    '''
    (list, list) --> list

    list1: the first list
    list2: the second list

    This function will return a new list by removing the characters that are
    the same and in the same position in both list1 and list2. The new list
    will contain only the characters from the first list that weren't the same
    but were at the same position in both lists

    >>>remove_fully_correct(['g', 'b', 'o', 'p'], ['g', 'b', 'y', 'r']
    ['o', 'p']
    '''

    length = len(list1)
    new_list = []

    for index in range(0, length):
        if list1[index] != list2[index]:
            new_list.append(list1[index])

    return new_list


def find_colour_correct(answer, guess):
    '''
    (list, list) --> list

    answer: the code generated by the program that the user has to correctly
    identify
    guess: the guess submitted by the user of what they think the answer is

    The function will return a list containing 'w' for every colour that was
    present in both the answer list and the guess list but was in a
    different position in both lists.

    >>>find_colour_correct(['r', 'r', 'b', 'p'], ['o', 'b', 'r', 'y']
    ['w', 'w']
    '''

    re_guess = remove_fully_correct(guess, answer)
    re_answer = remove_fully_correct(answer, guess)

    count = 0
    feedback = []

    for index in range(0, len(re_guess)):
        if re_answer.count(re_guess[index]) >= 1:
            count += 1
            re_answer.remove(re_guess[index])

    for num in range(0, count):
        feedback.append('w')

    return feedback


def print_game(guesses, clues):
    '''
    (list, list) --> combination of both lists

    guesses: all the guesses that the user has submitted in a list
    clues: the corresponding clues, 'b' or 'w', for each guess that the user
    has submitted

    The function ouputs to the screen the guesses the user has made and the
    clues received for each guess. Corresponding guesses and clues are
    separated by a tab. Each guess and clue sublist is printed below the proper
    heading (Guesses or Clues) and on different lines

    >>>print_game(guesses, clues)
    Guesses     Clues
    b b b b     b
    b g g g 	b w
    '''

    print('Guesses ', end='\t')
    print('Clues ', end='\n')

    for index in range(0, len(guesses)):
        print(guesses[index], end='\t')
        print(clues[index], end='\n')

    print(" ")

if __name__ == '__main__':

    charc = 'roygbiv'  
    code_str = ''  
    guess = ''  
    guesses = []  
    clues = []  
    prompt = "Please enter your guess: "
    reprompt = "Please enter your guess again of length four using the letters"
    tries = 1 

    code = create_code(charc, 4)

    for item in code:
        code_str = code_str + str(item)

    print(' ')
    print('***********************')
    print('Welcome to Mastermind!')
    print('***********************')
    print('Mastermind is a code-breaking game where the user (you) must use')
    print('logic and strategy to figure out the computer\'s 4-letter code.')
    print(' ')
    print('The rules of the game are simple.')
    print(' ')
    print('1. The only characters the code will contain are: R, O, G, Y, B, I, V.')
    print('2. Each character can appear in the code between 0 to 4 times.')
    print('3. In order to win, you must determine which character(s) appear in the code')
    print('as well as their exact position within 10 tries.')
    print('4. You are provided with clues for each guess. A \'b\' as a clue means that')
    print('one of the characters in your guess is present in the code and is in its')
    print('its correct position. A \'w\' as a clue means that one of the characters in')
    print('your guess is present in the code but is in the incorrect position.')
    print(' ')
    print('The computer has chosen a 4-letter code.')
    print(' ')

    guess = input(prompt)
    guess = guess.lower()
    print(' ')

    while guess != code_str and tries <= 10:

        guess_str = ''  
        clue_str = ''  
        guess_list = []  
        blacks = []  
        whites = []

        # creates a new guess string with space between each characters and
        # adds each characters as an item to the guess list

        for char in guess:
            guess_str += char + ' '
            guess_list.append(char)

        # only if the guess is valid is it checked, otherwise the programs
        # prompts the user to guess again

        if valid(guess_list, charc, 4):
            tries += 1  # keeps track of all the tries

            blacks = (find_fully_correct(code, guess_list))

            # adds the 'b' clues to the clue string

            for item in blacks:
                clue_str += item + ' '

            whites = (find_colour_correct(code, guess_list))

            # adds the 'w' clues to the clue string

            for item in whites:
                clue_str += item + ' '

            guesses.append(guess_str)  # adds each guess to the master list
            clues.append(clue_str)  # adds the clues to the master list

            print_game(guesses, clues)  # prints the list of guesses and clues

            if tries <= 10:
                guess = input(prompt)
                guess = guess.lower()
                print(" ")
        else:
            guess = input(prompt)
            guess = guess.lower()
            print(" ")

    if tries > 10:
        print("You lose! The correct code was " + code_str + ".")
    elif guess == code_str:
        print("Congratulations! It took you " + str(tries), end='')
        print(" guesses to find the code.")
    
    print(' ')